name: Deploy to Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o -t StrictHostKeyChecking=no divanof@147.45.254.214 <<EOF
            cd /home/gameton2
            git pull origin master
            cd backend
            ${{ secrets.SUDO_PASS }} | sudo --stdin docker-compose up --build -d
            cd ../frontend
            ${{ secrets.SUDO_PASS }} | sudo --stdin docker-compose up --build -d
          EOF
