name: Deploy to Server

on:
  push:
    branches:
      - test_deploy
  pull_request:
    branches:
      - test_deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -tt -i <(echo "${{ secrets.SSH_KEY }}") divanof@147.45.254.214 << EOF
            cd /home/gameton2
            git pull origin master
            
            # Запуск docker-compose для backend
            echo "${{ secrets.SUDO_PASS }}" | sudo -S docker-compose up --build -d backend
            
            # Запуск docker-compose для frontend
            echo "${{ secrets.SUDO_PASS }}" | sudo -S docker-compose up --build -d frontend
          EOF
